### ISSUE TITLE
Bug in jacobian background simulation stratosphere

### ISSUE THREAD

**Issue by eastjames** [geoschem/integrated_methane_inversion#257]
### Name and Institution (Required)

Name: James East
Institution: ACMG

### Description of your issue or question

I ran into a bug background simulation for the jacobian runs. This simulation should have 0 emissions, but a pattern that looks like numerical instability shows up partway through the simulation. The CH4 concentrations blow up to unphysical values (~600,000 ppb)

The plots show simple average CH4 from the GEOS-Chem SpeciesConc files. The bug appears to happen in the stratosphere.

This is using lognormal errors and the `feature/2d_sensitivities` branch. The error is in the GEOS-Chem output and doesn't result from any IMI changes in that branch.

![curtainbug](https://github.com/user-attachments/assets/184cb644-4df6-44d5-9d79-0f6d9f238d1e)

![bug](https://github.com/user-attachments/assets/0235aa22-ec09-4b2a-ae4a-c4dbe7952742)

**Comment by eastjames** [comment]
Tagging @msulprizio

**Comment by eastjames** [comment]
Halving the advection time step in `geoschem_config.yml` solved the issue. This suggests the problem is most likely related to the CFL condition being violated, pointed out by @msulprizio and @hannahnesser in offline conversations.

Old:
```yaml
#============================================================================
# Timesteps settings
#============================================================================
timesteps:
  transport_timestep_in_s: 300
```

New:
```yaml
#============================================================================
# Timesteps settings
#============================================================================
timesteps:
  transport_timestep_in_s: 150
```
