### ISSUE TITLE
Running IMI in docker container

### ISSUE THREAD

**Issue by pradhyumna85** [geoschem/integrated_methane_inversion#99]
Hi,
I was thinking if [this](https://hub.docker.com/layers/geoschem/gcclassic/13.3.3/images/sha256-60d6d58e84fb223004d41479a1ebd08f331446e9324b52d1e37a140bb1341872?context=explore) docker image (has compiled gcclassic binary and spack there) can be used to run IMI?

Do we have examples or guilde related to this ?

**Comment by laestrada** [comment]
Hi @pradhyumna85, 

We are planning to create a purpose-built IMI docker container. I currently have a branch feature/imi_dockerfile with a [dockerfile](https://github.com/geoschem/integrated_methane_inversion/blob/feature/imi_dockerfile/resources/containers/Dockerfile) that builds spack, conda, and the dependencies for running gcclassic. At this point it is untested and I need to update the dockerfile to install the IMI-specific conda environment and slurm, but it is probably better equipped than the gcclassic 13.3.3.

If there is enough interest in an IMI docker container we can increase the priority. May I ask what you are planning to use the container for?

**Comment by pradhyumna85** [comment]
My thinking and usecase is that - having a docker image for a software like gcclassic and Integrated methane inversion makes is effortlessly easy to quicky start running/learning and testing without going through the pain of compilation from source and manually installing all then dependencies.

**Comment by pradhyumna85** [comment]
Hi @laestrada,
How can I pull **753979222379.dkr.ecr.us-east-1.amazonaws.com/imi-docker-repository:latest** to my pc?

Docker pull output gives error regarding credentials on my machine:
`docker pull 753979222379.dkr.ecr.us-east-1.amazonaws.com/imi-docker-repository:latest`
>Error response from daemon: Head "https://753979222379.dkr.ecr.us-east-1.amazonaws.com/v2/imi-docker-repository/manifests/latest": no basic auth credentials

**Comment by laestrada** [comment]
Hi @pradhyumna85, 

The docker image listed here is still in development and not quite ready for public distribution, so the repository for the built image is not yet public. 

If you'd like to test it out before official release, you can feel free to build the images yourself by slightly modifying the dockerfiles in my docker container branch. Specifically, first build the dockerfile in `integrated_methane_inversion/resources/containers/base-image/` (this installs all the dependencies needed for the IMI) and then modify the dockerfile in `integrated_methane_inversion/resources/containers/` to use the base-image as the starting point. The second dockerfile adds the imi and geoschem source code.

**Comment by pradhyumna85** [comment]
Okay @laestrad, completely make sense.
Have you tested running IMI using the latest docker image? Like is it running successfully in some simple tests?

**Comment by laestrada** [comment]
It more or less works, but does not efficiently allocate the resources given by the host resources yet.

**Comment by pradhyumna85** [comment]
@laestrada, what kind of problem is currently there, like it is running slow on some specific parts of run_imi.sh scripts?

**Comment by laestrada** [comment]
Glad to hear you got it working! Mainly the issue is resource allocation with sbatch. Specifically when running the jacobian simulations we use sbatch to run simulations in parallel, but currently we do not have an automated method for specifying the memory allocated to each jacobian simulation, so it only runs a few simulations at a time (default mem is too much). Like you said, it works, but it is slow. Working on a fix.

FYI You can also pass in your aws credentials as [environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) and specify them in your docker run command.

**Comment by pradhyumna85** [comment]
@laestrada, thank you for the info. How much time the default yml case takes to run usually in non container env, just to have a reference?

**Comment by pradhyumna85** [comment]
@laestrada,
Did you tried various slurm parameters, in slurm config and or passing as sbatch parameters.?

[https://slurm.schedmd.com/slurm.conf.html](https://slurm.schedmd.com/slurm.conf.html)
DefMemPerCPU, MaxMemPerCPU

**Comment by laestrada** [comment]
@pradhyumna85 runtime depends on the number of cores and memory, but using a c5.9xlarge instance on aws we see:


IMI Runtime | Total Input Data | GEOS-Chem NA Met Fields | Boundary Conditions | HEMCO | TROPOMI data
-- | -- | -- | -- | -- | --
65 Minutes | 28GB | 21GB | 113MB | 3GB | 4.3GB

I am updating the IMI config file to let users adjust the amount of simulation memory and cpus, which should fix this. Something we needed to do anyways to accommodate varying region of interest sizes.

**Comment by pradhyumna85** [comment]
@laestrada,
Thank you for the info and update.

**Comment by pradhyumna85** [comment]
@laestrada,
I ran 1 case (_**input yml is given below**_), but the **imi_output.log** is stuck at:
```
=== DONE CREATING PREVIEW RUN DIRECTORY ===

=== RUNNING IMI PREVIEW ===
Submitted batch job 3
```

I have been waiting for it for about 3 hours. Let me know, what can be done to fix this.

**squeue** output:
```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                 3     debug Test_Per     root PD       0:00      1 (Resources)
                 2     debug run_imi.     root  R    2:59:02      1 d3c3e9775010
```

System:
- Docker on Windows
- Machine: 8 CPU (16 with hyperthreading) - Intel xeon, 32 GB RAM

input yml:
```yml
## IMI configuration file
## Documentation @ https://imi.readthedocs.io/en/latest/getting-started/imi-config-file.html

## General
RunName: "Test_Permian_3days_inv"
isAWS: true
UseSlurm: true
SafeMode: true

## Period of interest
StartDate: 20180501
EndDate: 20180503
SpinupMonths: 1

## Region of interest
##   These lat/lon bounds are only used if CreateAutomaticRectilinearStateVectorFile: true
##   Otherwise lat/lon bounds are determined from StateVectorFile
LonMin: -105
LonMax: -103
LatMin: 31
LatMax: 33

## Use nested grid simulation?
##   Must be "true" for IMI regional inversions
NestedGrid: true

## Select nested grid region (for using pre-cropped meteorological fields)
##   Current options are listed below with ([lat],[lon]) bounds:
##     "AF" : Africa ([-37,40], [-20,53])
##     "AS" : Asia ([-11,55],[60,150]) 
##     "EU" : Europe ([33,61],[-30,70])
##     "ME" : Middle East ([12,44], [-20,70])
##     "NA" : North America ([10,70],[-140,-40])
##     "OC" : Oceania ([-50,5], [110,180])
##     "RU" : Russia ([41,83], [19,180])
##     "SA" : South America ([-59,16], [-88,-31])
##     ""   : Use for global met fields (global simulation/custom nested grids)
##   For example, if the region of interest is in Europe ([33,61],[-30,70]), select "EU".
NestedRegion: "NA"

## State vector
CreateAutomaticRectilinearStateVectorFile: true
nBufferClusters: 8
BufferDeg: 5
LandThreshold: 0.25

## Clustering Options
ReducedDimensionStateVector: false
ClusteringPairs:
  - [1, 15]
  - [2, 24]
ForcedNativeResolutionElements: 
  - [31.5, -104]
  
## Custom state vector
StateVectorFile: "/home/al2/integrated_methane_inversion/resources/statevectors/StateVector.nc"
ShapeFile: "/home/al2/integrated_methane_inversion/resources/shapefiles/PermianBasin_Extent_201712.shp"

## Inversion
PriorError: 0.5
ObsError: 15
Gamma: 1.0
PrecomputedJacobian: false

## Grid
##   Select "0.25x0.3125" and "geosfp", or "0.5x0.625" and "merra2"
Res: "0.25x0.3125"
Met: "geosfp"

## Setup modules
##   Turn on/off different steps in setting up the inversion 
SetupTemplateRundir: true
SetupSpinupRun: true
SetupJacobianRuns: true
SetupInversion: true
SetupPosteriorRun: true

## Run modules
##   Turn on/off different steps in performing the inversion
RunSetup: true
DoSpinup: true
DoJacobian: true
DoInversion: true
DoPosterior: true

## IMI preview
DoPreview: true
DOFSThreshold: 0

##====================================================================
##
## Advanced Settings (optional)
##
##====================================================================

## These settings are intended for advanced users who wish to:
##   a. modify additional GEOS-Chem options, or
##   b. run the IMI on a local cluster.
## They can be ignored for any standard cloud application of the IMI.

##--------------------------------------------------------------------
## Additional settings for GEOS-Chem simulations
##--------------------------------------------------------------------

## Jacobian settings
PerturbValue: 1.5

## Apply scale factors from a previous inversion?
UseEmisSF: false
UseOHSF: false

## Save out hourly diagnostics from GEOS-Chem?
## For use in satellite operators via post-processing -- required for TROPOMI
## inversions
HourlyCH4: true

## Turn on planeflight diagnostic in GEOS-Chem?
## For use in comparing GEOS-Chem against planeflight data. The path
## to those data must be specified in input.geos.
PLANEFLIGHT: false

## Turn on old observation operators in GEOS-Chem?
## These will save out text files comparing GEOS-Chem to observations, but have
## to be manually incorporated into the IMI
GOSAT: false
TCCON: false
AIRS: false

##--------------------------------------------------------------------
## Settings for running on a local cluster
##--------------------------------------------------------------------

## Path for IMI runs and output
OutputPath: "/home/al2/imi_output_dir"

## Path to GEOS-Chem input data
DataPath: "/home/al2/ExtData"

## Environment files
CondaFile: "/opt/conda/etc/profile.d/conda.sh"
CondaEnv: "imi_env"

## Download initial restart file from AWS S3?
RestartDownload: true

## Path to initial GEOS-Chem restart file + prefix
##   ("YYYYMMDD_0000z.nc4" will be appended)
RestartFilePrefix: "/home/al2/ExtData/BoundaryConditions/GEOSChem.BoundaryConditions."
RestartFilePreviewPrefix: "/home/al2/ExtData/BoundaryConditions/GEOSChem.BoundaryConditions."

## Path to GEOS-Chem boundary condition files (for nested grid simulations)
BCpath: "/home/al2/ExtData/BoundaryConditions"

## Options to download missing GEOS-Chem input data from AWS S3
##   NOTE: You will be charged if your ec2 instance is not in the
##         us-east-1 region.
PreviewDryRun: true
SpinupDryrun: true
ProductionDryRun: true
PosteriorDryRun: true
BCdryrun: true
```

---

**Comment by laestrada** [comment]
I suspect that because there are no slurm resources specified in run_imi.sh it is taking all available resources and so the secondary sbatch job has no resources available to start. you can run `scontrol show job <id-number>` for more information on the job. I would try updating the entrypoint.sh to launch with memory and cpus specified eg:

`sbatch -W --mem 2000 -c 1 run_imi.sh resources/containers/container_config.yml; wait;`

Or alternatively just do:
`./run_imi.sh resources/containers/container_config.yml`

Please report back if this works... I have only tested using a c5.9xlarge instance (36 cores, 72GB memory) so am curious if it works with your current system.

**Comment by pradhyumna85** [comment]
@laestrada,
> bash-4.2# **scontrol show job 3**
```
JobId=3 JobName=Test_Permian_3days_inv_Preview.run
   UserId=root(0) GroupId=root(0) MCS_label=N/A
   Priority=4294901758 Nice=0 Account=(null) QOS=(null)
   JobState=PENDING Reason=Resources Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=UNLIMITED TimeMin=N/A
   SubmitTime=2023-05-04T16:11:22 EligibleTime=2023-05-04T16:11:22
   AccrueTime=2023-05-04T16:11:22
   StartTime=2024-05-03T15:56:17 EndTime=Unknown Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2023-05-04T18:02:15 Scheduler=Main
   Partition=debug AllocNode:Sid=d3c3e9775010:20704
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=
   NumNodes=1-1 NumCPUs=15 NumTasks=1 CPUs/Task=15 ReqB:S:C:T=0:0:*:*
   ReqTRES=cpu=15,mem=15902M,node=1,billing=15
   AllocTRES=(null)
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=15 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/al2/imi_output_dir/Test_Permian_3days_inv/preview_run/Test_Permian_3days_inv_Preview.run
   WorkDir=/home/al2/imi_output_dir/Test_Permian_3days_inv/preview_run
   StdErr=/home/al2/imi_output_dir/Test_Permian_3days_inv/preview_run/slurm-3.out
   StdIn=/dev/null
   StdOut=/home/al2/imi_output_dir/Test_Permian_3days_inv/preview_run/slurm-3.out
   Power=
   MailUser=root MailType=END
```

Let me know what you think from the above output.

I will also try the changes you suggested and report you back.

**Comment by laestrada** [comment]
Yeah `JobState=PENDING Reason=Resources` implies the resources requested to run the job with are not free (15 cores and 15902MB). This will wont be an issue once I finish my branch allowing specification of memory and CPU number from the config file. For now changing entrypoint.sh to use my second suggestion should work....

**Comment by laestrada** [comment]
Yes, you should replace that command with `./run_imi.sh resources/containers/container_config.yml`. The issue is that the preview slurm job, by default, is requesting all resources in the container. This means that it is waiting for job 5 to finish and free up resources, but job 5 is waiting for job 6 to finish.. and so on. So until we have config variables setup to allocate resources for the various sbatch jobs that get run the run command for the imi will need to be called directly.

**Comment by pradhyumna85** [comment]
@laestrada I ran successfully after the latest commits. Thanks a lot for the support.
However, for one of the case run - Permian with 4 days window, I see some errors in the spin-up logs:

```
=== DONE CREATING TEMPLATE RUN DIRECTORY ===

=== CREATING IMI PREVIEW RUN DIRECTORY ===
mkdir: created directory ‘preview_run’

Executing dry-run for preview run...
Log with unique file paths written to: log.dryrun.unique
Downloading data from amazon

=== DONE CREATING PREVIEW RUN DIRECTORY ===

=== RUNNING IMI PREVIEW ===
Submitted batch job 1
Submitted batch job 2

=== DONE RUNNING IMI PREVIEW ===
src/components/preview_component/preview.sh: line 106: bc: command not found
src/components/preview_component/preview.sh: line 106: [: : integer expression expected

=== CREATING SPINUP RUN DIRECTORY ===
mkdir: created directory ‘spinup_run’

WARNING: Changing restart field entry in HEMCO_Config.rc to read the field from a boundary condition file. Please revert SpeciesBC_ back to SpeciesRst_ for subsequent runs.

Executing dry-run for spinup run...
```
___

error lines:
```
src/components/preview_component/preview.sh: line 106: bc: command not found
src/components/preview_component/preview.sh: line 106: [: : integer expression expected
```

input yaml:
```yaml
## IMI configuration file
## Documentation @ https://imi.readthedocs.io/en/latest/getting-started/imi-config-file.html

## General
RunName: "Test_Permian_4days"
isAWS: true
UseSlurm: true
SafeMode: true

## Period of interest
StartDate: 20221225
EndDate: 20221230
SpinupMonths: 1

## Region of interest
##   These lat/lon bounds are only used if CreateAutomaticRectilinearStateVectorFile: true
##   Otherwise lat/lon bounds are determined from StateVectorFile
LonMin: -105
LonMax: -103
LatMin: 31
LatMax: 33

## Use nested grid simulation?
##   Must be "true" for IMI regional inversions
NestedGrid: true

## Select nested grid region (for using pre-cropped meteorological fields)
##   Current options are listed below with ([lat],[lon]) bounds:
##     "AF" : Africa ([-37,40], [-20,53])
##     "AS" : Asia ([-11,55],[60,150]) 
##     "EU" : Europe ([33,61],[-30,70])
##     "ME" : Middle East ([12,44], [-20,70])
##     "NA" : North America ([10,70],[-140,-40])
##     "OC" : Oceania ([-50,5], [110,180])
##     "RU" : Russia ([41,83], [19,180])
##     "SA" : South America ([-59,16], [-88,-31])
##     ""   : Use for global met fields (global simulation/custom nested grids)
##   For example, if the region of interest is in Europe ([33,61],[-30,70]), select "EU".
NestedRegion: "NA"

## State vector
CreateAutomaticRectilinearStateVectorFile: true
nBufferClusters: 8
BufferDeg: 5
LandThreshold: 0.25

## Clustering Options
ReducedDimensionStateVector: false
ClusteringPairs:
  - [1, 15]
  - [2, 24]
ForcedNativeResolutionElements: 
  - [31.5, -104]
  
## Custom state vector
StateVectorFile: "/home/al2/integrated_methane_inversion/resources/statevectors/StateVector.nc"
ShapeFile: "/home/al2/integrated_methane_inversion/resources/shapefiles/PermianBasin_Extent_201712.shp"

## Inversion
PriorError: 0.5
ObsError: 15
Gamma: 1.0
PrecomputedJacobian: false

## Grid
##   Select "0.25x0.3125" and "geosfp", or "0.5x0.625" and "merra2"
Res: "0.25x0.3125"
Met: "geosfp"

## Setup modules
##   Turn on/off different steps in setting up the inversion 
SetupTemplateRundir: true
SetupSpinupRun: true
SetupJacobianRuns: true
SetupInversion: true
SetupPosteriorRun: true

## Run modules
##   Turn on/off different steps in performing the inversion
RunSetup: true
DoSpinup: true
DoJacobian: true
DoInversion: true
DoPosterior: true

## IMI preview
DoPreview: true
DOFSThreshold: 0

##====================================================================
##
## Advanced Settings (optional)
##
##====================================================================

## These settings are intended for advanced users who wish to:
##   a. modify additional GEOS-Chem options, or
##   b. run the IMI on a local cluster.
## They can be ignored for any standard cloud application of the IMI.

##--------------------------------------------------------------------
## Additional settings for GEOS-Chem simulations
##--------------------------------------------------------------------

## Jacobian settings
PerturbValue: 1.5

## Apply scale factors from a previous inversion?
UseEmisSF: false
UseOHSF: false

## Save out hourly diagnostics from GEOS-Chem?
## For use in satellite operators via post-processing -- required for TROPOMI
## inversions
HourlyCH4: true

## Turn on planeflight diagnostic in GEOS-Chem?
## For use in comparing GEOS-Chem against planeflight data. The path
## to those data must be specified in input.geos.
PLANEFLIGHT: false

## Turn on old observation operators in GEOS-Chem?
## These will save out text files comparing GEOS-Chem to observations, but have
## to be manually incorporated into the IMI
GOSAT: false
TCCON: false
AIRS: false

## resources to allocate to slurm jobs
SimulationCPUs: 32
SimulationMemory: 32000
JacobianCPUs: 1
JacobianMemory: 2000
RequestedTime: "0-6:00"

##--------------------------------------------------------------------
## Settings for running on a local cluster
##--------------------------------------------------------------------

## Path for IMI runs and output
OutputPath: "/home/al2/imi_output_dir"

## Path to GEOS-Chem input data
DataPath: "/home/al2/ExtData"

## Environment files
CondaFile: "/opt/conda/etc/profile.d/conda.sh"
CondaEnv: "imi_env"

## Download initial restart file from AWS S3?
RestartDownload: true

## Path to initial GEOS-Chem restart file + prefix
##   ("YYYYMMDD_0000z.nc4" will be appended)
RestartFilePrefix: "/home/al2/ExtData/BoundaryConditions/GEOSChem.BoundaryConditions."
RestartFilePreviewPrefix: "/home/al2/ExtData/BoundaryConditions/GEOSChem.BoundaryConditions."

## Path to GEOS-Chem boundary condition files (for nested grid simulations)
BCpath: "/home/al2/ExtData/BoundaryConditions"

## Options to download missing GEOS-Chem input data from AWS S3
##   NOTE: You will be charged if your ec2 instance is not in the
##         us-east-1 region.
PreviewDryRun: true
SpinupDryrun: true
ProductionDryRun: true
PosteriorDryRun: true
BCdryrun: true
```

Let me know your thoughts.

thank you.
